### ISSUE TITLE
Ads SDK 5.5.0: Invalid manifest

### ISSUE THREAD

**Issue by Reactor13** [yandexmobile/yandex-ads-sdk-swift#12]
Приветствую,

Невозможно подключить SDK 5.5.0 в новый проект, тк возникает ошибка:
<img width="1083" alt="Снимок экрана 2023-02-21 в 21 53 25" src="https://user-images.githubusercontent.com/7979883/220456749-12d2b6e4-61cf-405f-b98b-d6f916107e16.png">

Невозможно также обновить с 5.4.0 на 5.5.0 в существующем проекте:
<img width="547" alt="Снимок экрана 2023-02-21 в 21 58 05" src="https://user-images.githubusercontent.com/7979883/220456951-58e8c974-94c2-483a-9142-0e3f2fbdfe82.png">

Xcode 14.2
Также подключены: 
* https://github.com/firebase/firebase-ios-sdk.git
* https://github.com/googleads/swift-package-manager-google-mobile-ads.git

**Comment by mobile-ads-github** [comment]
Добрый день! Спасибо за обращение, смотрим на проблему.

**Comment by mobile-ads-github** [comment]
Tag 5.5.0 pointed to the forked repository. This is fixed:

https://github.com/yandexmobile/yandex-ads-sdk-swift/releases/tag/5.5.0

**Comment by Reactor13** [comment]
Прошу прощения, но я не очень понял как это исправляет проблему.
Так же я не понял - это моя частная проблема или действительно есть проблема в манифесте репозитория. Если так, то как тогда им пользоваться?

Попытка добавить репозиторий по ссылке выше, тоже не приводит к успеху.

<img width="854" alt="Снимок экрана 2023-03-03 в 13 31 26" src="https://user-images.githubusercontent.com/7979883/222720957-543c8191-064e-4419-b6cd-e94602958ac9.png">

**Comment by mobile-ads-github** [comment]
> Прошу прощения, но я не очень понял как это исправляет проблему.

Подскажите, пожалуйста, если вы скачиваете репозиторий и после этого устанавливаете, это решает проблему?

Можете полностью удалить SDK и добавить его заново?

**Comment by Reactor13** [comment]
> > Прошу прощения, но я не очень понял как это исправляет проблему.
> 
> Подскажите, пожалуйста, если вы скачиваете репозиторий и после этого устанавливаете, это решает проблему?
> 
> Можете полностью удалить SDK и добавить его заново?

1. У меня нет задачи как самоцели перейти на версию 5.5.0, 5.4.0 - устанавливается через SwiftPackageManager.

2. Вы могли бы все же ответить - проблема локально у меня или нет? Я вроде как хочу помочь решить проблему с репозиторием. Если будет исправлено в будущих версиях - прекрасно, буду ждать. Если проблема моя локальная, буду разбираться. 

3. Нет просто скачать репозиторий и установить его я не пробовал. 
Сначала долго настраивал чтобы через SwiftPackageManager заработала 5.4.0 (посмотрите мой предыдущий [issue](https://github.com/yandexmobile/yandex-ads-sdk-swift/issues/9), при этом документация еще так и не обновлена, что YandexMobileAdsBundle лежит теперь совсем в другом месте), а теперь перейти на ручную установку? Смысла в этом нет на мой взгляд.

**Comment by VladimirAvstriychenko** [comment]
@Reactor13 Проблема не только у вас - у нас то же самое. Сидим, ждем
