### ISSUE TITLE
Отсутствует релиз 5.7.0

### ISSUE THREAD

**Issue by Reactor13** [yandexmobile/yandex-ads-sdk-swift#16]
Приветствую, 

Последняя версия SDK 5.7.0, но в релизах последняя версия 5.6.0.
Сейчас через SwiftPackageManager можно установить только 5.6.0.

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 24635089. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp18.06.2023, 03:35, "Reactor13" ***@***.***>:
Приветствую,
Последняя версия SDK 5.7.0, но в релизах последняя версия 5.6.0.
Сейчас через SwiftPackageManager можно установить только 5.6.0.

**Comment by Reactor13** [comment]
<img width="1210" alt="Снимок экрана 2023-06-18 в 03 35 20" src="https://github.com/yandexmobile/yandex-ads-sdk-swift/assets/7979883/66a94a10-202c-4da2-b776-0acbe5fb266a">

**Comment by mobile-ads-github** [comment]
Здравствуйте! Обновили версию для SwiftPackageManager
