### ISSUE TITLE
Не компилируется версия 6.1.0 (+ DivKit 28.8.0)

### ISSUE THREAD

**Issue by AndreVasilev** [yandexmobile/yandex-ads-sdk-swift#23]
Добавил библиотеку через SPM версии 6.1.0

При сборке получил ошибку полностью идентичную той, которая описана здесь:
https://github.com/yandexmobile/yandex-ads-sdk-ios/issues/180

По аналогии с рекомендацией в явном виде добавил пакет DivKit 28.4.0 - тогда проект удалось собрать без ошибок

**Comment by mobile-ads-github** [comment]
Спасибо за обращение. Перевыпустили [релиз 6.1.0](https://github.com/yandexmobile/yandex-ads-sdk-swift/releases/tag/6.1.0).

**Comment by AndreVasilev** [comment]
Кажется, проблема сохраняется. 
После сброса кэша по-прежнему подгружается DivKit 28.8.0
Повторное скачивание и добавление в проект MobileAdsBundle тоже не повлияло на ситуацию

**Comment by mobile-ads-github** [comment]
Да действительно, тэг `6.1.0` оставался прежний. Удалили тэг и выпустили релиз еще раз, попробуйте снова.

**Comment by AndreVasilev** [comment]
Спасибо!
