### ISSUE TITLE
Невозможно выполнить сборку в XCode 14.2 используя SwiftPackageManager

### ISSUE THREAD

**Issue by Reactor13** [yandexmobile/yandex-ads-sdk-swift#9]
Не знаю, где лучше разместить данную проблему.
Вот здесь полное описание: https://github.com/yandexmobile/yandex-ads-sdk-ios/issues/141#issue-1536321825

**Comment by mobile-ads-github** [comment]
Здравствуйте!
Спасибо за информацию, поправили ошибку, рекомендуем удалить package из проекта и добавить повторно, для удаления кешей.
Актуальная версия 5.4.0.

**Comment by Reactor13** [comment]
> Здравствуйте! Спасибо за информацию, поправили ошибку, рекомендуем удалить package из проекта и добавить повторно, для удаления кешей. Актуальная версия 5.4.0.

Сделал, но к сожалению ничего не изменилось от слова "совсем".
Что может быть не так?

**Comment by Reactor13** [comment]
Попробовал установить через CocoaPods. Насколько я понял, DivKit все равно не устанавливается при подключении через SwiftPackageManager

YandexMobileAdsInstream также не устанавливается

**Comment by mobile-ads-github** [comment]
Здравствуйте!
Посмотрите пожалуйста на текущий YandexMobileAdsPackage/Package.swift в вашем проекте.
Если в нем нету зависимости DivKit - проблема в cache.
Почистить можно выполнив File -> Packages -> Reset Package Caches.
Если не помогло, можно воспользоваться рядом решений из [stackoverflow](https://stackoverflow.com/a/68876107)

**Comment by Reactor13** [comment]
> Здравствуйте! Посмотрите пожалуйста на текущий YandexMobileAdsPackage/Package.swift в вашем проекте. Если в нем нету зависимости DivKit - проблема в cache. Почистить можно выполнив File -> Packages -> Reset Package Caches. Если не помогло, можно воспользоваться рядом решений из [stackoverflow](https://stackoverflow.com/a/68876107)

После сброса кэша проблема решилась. Спасибо.

**Comment by Reactor13** [comment]
Что касается YandexMobileAdsBundle.bundle:

1. Правильно ли, что его теперь нужно искать по artifacts? 
<img width="582" alt="Снимок экрана 2023-01-18 в 08 52 54" src="https://user-images.githubusercontent.com/7979883/213114639-bbf4dbb6-970f-481f-b982-46d2c728f512.png">


2. Насколько вообще его необходимо подключать? RewardedAd отобразилось без подключения.

**Comment by mobile-ads-github** [comment]
Здравствуйте!
> Что касается YandexMobileAdsBundle.bundle:
> 
> 1. Правильно ли, что его теперь нужно искать по artifacts?

 Правильно
 
> 2. Насколько вообще его необходимо подключать? RewardedAd отобразилось без подключения.

Подключать необходимо, использование bundle зависит от внутренней логики сдк.
Корректность подключения бандла можно увидеть в логах под тегом [YandexAdsIntegrityCheck].
